name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test -- --coverage

  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SCA Scan
        uses: dependabot/fetch-metadata@v1
      - name: SAST Scan
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=password-manager \
            -Dsonar.sources=./src

  deploy:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/<org>/password-manager:latest .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/<org>/password-manager:latest
      - name: Rollback on Failure
        if: failure()
        run: |
          kubectl rollout undo deployment/password-manager
